version: '3'
services: 
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    depends_on: 
      - api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - HOST=0.0.0.0